In [1]:
# Load the data
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [2]:
iris = load_iris(as_frame=True)
df = iris.frame
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [3]:
# Divide dataset
X = df[['sepal length (cm)', 'sepal width (cm)',	'petal length (cm)', 'petal width (cm)']]
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Build KNN model
knn = KNeighborsClassifier(n_neighbors = 1).fit(X_train, y_train)
y_pred = knn.predict(X_test)

# Evaluate the model
print(np.mean(y_test==y_pred))
print(knn.score(X_test, y_test))

0.9736842105263158
0.9736842105263158


---

In [4]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
 
iris_data = load_iris()
# This function returns a Bunch object, which directly inherits from Dict.
# It is similar to a dictionary and consists of key-value pairs.
# Can use bunch.keys(), bunch.values(), bunch.items(), etc.
print(type(iris_data)) 

# 'data' contains measurements of sepal length, sepal width,
# petal length, and petal width, formatted as a NumPy array
print(iris_data['data'])    # Flower sample data
print("Number of flower samples: {}".format(iris_data['data'].shape))   
print("First 5 flower samples: {}".format(iris_data['data'][:5])) 
 
# 0 represents setosa, 1 represents versicolor, 2 represents virginica
print(iris_data['target'])  # Labels
print(iris_data['target_names'])   # Flower species

# Construct training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(
    iris_data['data'], iris_data['target'], random_state=0)
print("Training sample data shape: {}".format(X_train.shape))
print("Training sample labels shape: {}".format(y_train.shape))
print("Testing sample data shape: {}".format(X_test.shape))
print("Testing sample labels shape: {}".format(y_test.shape))
 
# Construct KNN model
knn = KNeighborsClassifier(n_neighbors=1)
# knn = KNeighborsClassifier(n_neighbors=3)
 
# Train the model
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
 
# Evaluate the model accuracy
print("Accuracy: {:.2f}".format(np.mean(y_pred == y_test)))
print("Accuracy: {:.2f}".format(knn.score(X_test, y_test)))
 
# Make a prediction
X_new = np.array([[1.1, 5.9, 1.4, 2.2]])
prediction = knn.predict(X_new)
print("Predicted target class: {}".format(prediction))
print("Predicted target flower name: {}".format(iris_data['target_names'][prediction]))

<class 'sklearn.utils._bunch.Bunch'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7